name: Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-rc.2.22477.23

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.0

    - name: npm ci
      working-directory: src/Umbraco.Web.UI.Client
      run: npm ci --no-fund --no-audit --prefer-offline

    - name: gulp coreBuild
      working-directory: src/Umbraco.Web.UI.Client
      run: npx gulp coreBuild

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore -p:ContinuousIntegrationBuild=true

    - name: Pack
      run: dotnet pack umbraco.sln --configuration Release --no-build --output artifacts/nupkg

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'artifacts/nupkg'
